<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/shared/seguridad.php'; require_once dirname(__DIR__, 2) . '/shared/admin-flash.php'; require_once dirname(__DIR__, 2) . '/config/database.php'; require_once __DIR__ . '/includes/funciones-usuarios.php'; require_once __DIR__ . '/includes/consultas-usuarios.php';
requerirAdministradorUsuarios(); $id=idUsuarioValido($_GET['id_usuario']??null);
if($id===null){guardarModalAdmin('error','No fue posible cambiar la contraseña','El usuario indicado no es válido.');header('Location: '.appUrl('admin/usuarios/index.php'));exit;}
try{$user=obtenerUsuarioPorId(database(),$id);}catch(Throwable $exception){$reference=referenciaErrorUsuario('User password form error',$exception);guardarModalAdmin('error','No fue posible cambiar la contraseña','No se pudo completar la acción.',['reference'=>$reference]);header('Location: '.appUrl('admin/usuarios/index.php'));exit;}
if($user===null){guardarModalAdmin('error','No fue posible cambiar la contraseña','El usuario indicado no existe.');header('Location: '.appUrl('admin/usuarios/index.php'));exit;}
$state=consumirEstadoUsuario('password_'.$id);$errors=is_array($state['errors']??null)?$state['errors']:[];if($errors!==[]||isset($state['generalError'])){$adminModal=['type'=>'error','title'=>'No fue posible actualizar la contraseña','message'=>$errors!==[]?'Revisa los campos marcados antes de continuar.':(string)$state['generalError'],'reference'=>(string)($state['reference']??'')];}
$csrfToken=csrfToken();$pageTitle='Cambiar contraseña';$activeSection='usuarios';require dirname(__DIR__,2).'/shared/admin-header.php';require dirname(__DIR__,2).'/shared/admin-sidebar.php';?>
<main class="admin-main admin-users" id="contenido-principal"><header class="admin-page-header"><div><a class="admin-back-link" href="<?=escape(appUrl('admin/usuarios/index.php'))?>">Volver a usuarios</a><h1 class="admin-page-title">Cambiar contraseña</h1><p>Define una nueva clave para <?=escape((string)$user['nombre'])?>.</p></div></header><div class="admin-user-password-layout"><aside class="admin-user-security-card"><i class="bi bi-key-fill" aria-hidden="true"></i><span>Credencial protegida</span><strong><?=escape((string)$user['nombre'])?></strong><small><?=escape((string)$user['email'])?></small><p>La contraseña nunca se muestra ni se registra en logs. Se reemplazará por un hash seguro.</p></aside><form class="admin-user-form" method="post" action="<?=escape(appUrl('admin/usuarios/actualizar-password.php'))?>"><input type="hidden" name="csrf_token" value="<?=escape($csrfToken)?>"><input type="hidden" name="id_usuario" value="<?=$id?>"><section class="admin-user-form-card"><header><i class="bi bi-shield-lock-fill" aria-hidden="true"></i><div><span>Seguridad</span><h2>Nueva contraseña</h2><p>Utiliza al menos 8 caracteres.</p></div></header><div class="admin-form-grid"><div class="admin-field<?=isset($errors['password'])?' admin-field--invalid':''?>"><label for="password">Nueva contraseña *</label><input id="password" name="password" type="password" minlength="8" required autocomplete="new-password"><?php if(isset($errors['password'])):?><span class="admin-field__error"><?=escape((string)$errors['password'])?></span><?php endif;?></div><div class="admin-field<?=isset($errors['password_confirmacion'])?' admin-field--invalid':''?>"><label for="password_confirmacion">Confirmar contraseña *</label><input id="password_confirmacion" name="password_confirmacion" type="password" minlength="8" required autocomplete="new-password"><?php if(isset($errors['password_confirmacion'])):?><span class="admin-field__error"><?=escape((string)$errors['password_confirmacion'])?></span><?php endif;?></div></div><footer><a class="admin-button" href="<?=escape(appUrl('admin/usuarios/index.php'))?>">Cancelar</a><button class="admin-button admin-button--primary" type="submit"><i class="bi bi-key-fill" aria-hidden="true"></i> Actualizar contraseña</button></footer></section></form></div></main><?php require dirname(__DIR__,2).'/shared/admin-footer.php';?>

