<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/shared/seguridad.php'; require_once dirname(__DIR__, 2) . '/shared/admin-flash.php'; require_once __DIR__ . '/includes/funciones-usuarios.php';
requerirAdministradorUsuarios(); $state = consumirEstadoUsuario('crear'); $values = array_merge(valoresInicialesUsuario(), is_array($state['values'] ?? null) ? $state['values'] : []); $errors = is_array($state['errors'] ?? null) ? $state['errors'] : [];
if ($errors !== [] || isset($state['generalError'])) { $adminModal = ['type' => 'error', 'title' => 'No fue posible guardar el usuario', 'message' => $errors !== [] ? 'Revisa los campos marcados antes de continuar.' : (string) $state['generalError'], 'reference' => (string) ($state['reference'] ?? '')]; }
$csrfToken = csrfToken(); $pageTitle = 'Crear usuario'; $activeSection = 'usuarios'; require dirname(__DIR__, 2) . '/shared/admin-header.php'; require dirname(__DIR__, 2) . '/shared/admin-sidebar.php';
?>
<main class="admin-main admin-users" id="contenido-principal"><header class="admin-page-header"><div><a class="admin-back-link" href="<?= escape(appUrl('admin/usuarios/index.php')) ?>">Volver a usuarios</a><h1 class="admin-page-title">Crear usuario</h1><p>Entrega acceso seguro a un integrante del equipo.</p></div></header>
<form class="admin-user-form" method="post" action="<?= escape(appUrl('admin/usuarios/guardar.php')) ?>"><input type="hidden" name="csrf_token" value="<?= escape($csrfToken) ?>"><section class="admin-user-form-card"><header><i class="bi bi-person-plus-fill" aria-hidden="true"></i><div><span>Nuevo acceso</span><h2>Datos del usuario</h2><p>La contraseña se almacenará mediante un hash seguro.</p></div></header><div class="admin-form-grid">
<?php foreach ([['nombre','Nombre','text',120,'Nombre completo'],['email','Email','email',160,'usuario@coratto.cl']] as [$name,$label,$type,$max,$placeholder]): ?><div class="admin-field<?= isset($errors[$name]) ? ' admin-field--invalid' : '' ?>"><label for="<?= $name ?>"><?= $label ?> *</label><input id="<?= $name ?>" name="<?= $name ?>" type="<?= $type ?>" maxlength="<?= $max ?>" required autocomplete="<?= $name === 'email' ? 'email' : 'name' ?>" placeholder="<?= $placeholder ?>" value="<?= escape((string) $values[$name]) ?>"><?php if(isset($errors[$name])):?><span class="admin-field__error"><?= escape((string)$errors[$name]) ?></span><?php endif;?></div><?php endforeach; ?>
<div class="admin-field<?= isset($errors['rol']) ? ' admin-field--invalid' : '' ?>"><label for="rol">Rol *</label><select id="rol" name="rol" required><?php foreach(rolesUsuarios() as $value=>$label):?><option value="<?=escape($value)?>" <?=$values['rol']===$value?'selected':''?>><?=escape($label)?></option><?php endforeach;?></select><?php if(isset($errors['rol'])):?><span class="admin-field__error"><?=escape((string)$errors['rol'])?></span><?php endif;?></div>
<div class="admin-status-control"><div class="admin-status-control__copy"><strong>Usuario activo</strong><span>Podrá ingresar al administrador inmediatamente.</span></div><label class="admin-switch" for="activo"><input id="activo" name="activo" type="checkbox" value="1" <?= $values['activo'] ? 'checked' : '' ?>><span class="admin-switch__track" aria-hidden="true"></span><span class="admin-switch__label">Acceso habilitado</span></label></div>
<div class="admin-field<?= isset($errors['password']) ? ' admin-field--invalid' : '' ?>"><label for="password">Contraseña *</label><input id="password" name="password" type="password" minlength="8" required autocomplete="new-password"><p class="admin-field__help">Mínimo 8 caracteres.</p><?php if(isset($errors['password'])):?><span class="admin-field__error"><?=escape((string)$errors['password'])?></span><?php endif;?></div>
<div class="admin-field<?= isset($errors['password_confirmacion']) ? ' admin-field--invalid' : '' ?>"><label for="password_confirmacion">Confirmar contraseña *</label><input id="password_confirmacion" name="password_confirmacion" type="password" minlength="8" required autocomplete="new-password"><?php if(isset($errors['password_confirmacion'])):?><span class="admin-field__error"><?=escape((string)$errors['password_confirmacion'])?></span><?php endif;?></div>
</div><footer><a class="admin-button" href="<?=escape(appUrl('admin/usuarios/index.php'))?>">Cancelar</a><button class="admin-button admin-button--primary" type="submit"><i class="bi bi-person-plus-fill" aria-hidden="true"></i> Crear usuario</button></footer></section></form></main><?php require dirname(__DIR__,2).'/shared/admin-footer.php';?>

