<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/shared/seguridad.php'; require_once dirname(__DIR__, 2) . '/shared/admin-flash.php'; require_once dirname(__DIR__, 2) . '/config/database.php'; require_once __DIR__ . '/includes/funciones-usuarios.php'; require_once __DIR__ . '/includes/consultas-usuarios.php';
requerirAdministradorUsuarios(); $id = idUsuarioValido($_GET['id_usuario'] ?? null);
if ($id === null) { guardarModalAdmin('error','No fue posible editar el usuario','El usuario indicado no es válido.'); header('Location: '.appUrl('admin/usuarios/index.php')); exit; }
try { $user = obtenerUsuarioPorId(database(), $id); } catch(Throwable $exception) { $reference=referenciaErrorUsuario('User edit load error',$exception); guardarModalAdmin('error','No fue posible editar el usuario','No se pudo completar la acción.',['reference'=>$reference]); header('Location: '.appUrl('admin/usuarios/index.php')); exit; }
if ($user === null) { guardarModalAdmin('error','No fue posible editar el usuario','El usuario indicado no existe.'); header('Location: '.appUrl('admin/usuarios/index.php')); exit; }
$state=consumirEstadoUsuario('editar_'.$id); $values=array_merge(['nombre'=>(string)$user['nombre'],'email'=>(string)$user['email'],'rol'=>(string)$user['rol'],'activo'=>usuarioBooleano($user['activo'])],is_array($state['values']??null)?$state['values']:[]); $errors=is_array($state['errors']??null)?$state['errors']:[];
if($errors!==[]||isset($state['generalError'])){$adminModal=['type'=>'error','title'=>'No fue posible actualizar el usuario','message'=>$errors!==[]?'Revisa los campos marcados antes de continuar.':(string)$state['generalError'],'reference'=>(string)($state['reference']??'')];}
$isSelf=$id===usuarioActualId(); $csrfToken=csrfToken(); $pageTitle='Editar usuario'; $activeSection='usuarios'; require dirname(__DIR__,2).'/shared/admin-header.php'; require dirname(__DIR__,2).'/shared/admin-sidebar.php';
?>
<main class="admin-main admin-users" id="contenido-principal"><header class="admin-page-header"><div><a class="admin-back-link" href="<?=escape(appUrl('admin/usuarios/index.php'))?>">Volver a usuarios</a><h1 class="admin-page-title">Editar usuario</h1><p>Actualiza identidad, rol y disponibilidad del acceso.</p></div><a class="admin-button admin-button--primary" href="<?=escape(appUrl('admin/usuarios/cambiar-password.php?id_usuario='.$id))?>"><i class="bi bi-key-fill" aria-hidden="true"></i> Cambiar contraseña</a></header>
<div class="admin-user-edit-layout"><aside class="admin-user-security-card"><i class="bi bi-shield-lock-fill" aria-hidden="true"></i><span>Perfil interno</span><strong><?=escape((string)$user['nombre'])?></strong><small><?=escape((string)$user['email'])?></small><dl><div><dt>Creado</dt><dd><?=escape(formatearFechaUsuario($user['creado_en']))?></dd></div><div><dt>Último acceso</dt><dd><?=escape(formatearFechaUsuario($user['ultimo_acceso']))?></dd></div></dl><?php if($isSelf):?><p><i class="bi bi-info-circle-fill" aria-hidden="true"></i> Este es tu usuario actual. Su acceso y rol administrador están protegidos.</p><?php endif;?></aside>
<form class="admin-user-form" method="post" action="<?=escape(appUrl('admin/usuarios/actualizar.php'))?>"><input type="hidden" name="csrf_token" value="<?=escape($csrfToken)?>"><input type="hidden" name="id_usuario" value="<?=$id?>"><section class="admin-user-form-card"><header><i class="bi bi-pencil-square" aria-hidden="true"></i><div><span>Datos básicos</span><h2>Información del usuario</h2><p>La contraseña se gestiona desde una pantalla separada.</p></div></header><div class="admin-form-grid">
<?php foreach ([['nombre','Nombre','text',120],['email','Email','email',160]] as [$name,$label,$type,$max]):?><div class="admin-field<?=isset($errors[$name])?' admin-field--invalid':''?>"><label for="<?=$name?>"><?=$label?> *</label><input id="<?=$name?>" name="<?=$name?>" type="<?=$type?>" maxlength="<?=$max?>" required value="<?=escape((string)$values[$name])?>"><?php if(isset($errors[$name])):?><span class="admin-field__error"><?=escape((string)$errors[$name])?></span><?php endif;?></div><?php endforeach;?>
<div class="admin-field<?=isset($errors['rol'])?' admin-field--invalid':''?>"><label for="rol">Rol *</label><select id="rol" name="rol" required <?=$isSelf?'aria-describedby="rol-self-help"':''?>><?php foreach(rolesUsuarios() as $value=>$label):?><option value="<?=escape($value)?>" <?=$values['rol']===$value?'selected':''?>><?=escape($label)?></option><?php endforeach;?></select><?php if($isSelf):?><p class="admin-field__help" id="rol-self-help">Tu sesión debe conservar el rol administrador.</p><?php endif;?><?php if(isset($errors['rol'])):?><span class="admin-field__error"><?=escape((string)$errors['rol'])?></span><?php endif;?></div>
<div class="admin-status-control<?=isset($errors['activo'])?' admin-field--invalid':''?>"><div class="admin-status-control__copy"><strong>Usuario activo</strong><span><?=$isSelf?'No puedes desactivar tu propio acceso.':'Controla si puede iniciar sesión.'?></span><?php if(isset($errors['activo'])):?><span class="admin-field__error"><?=escape((string)$errors['activo'])?></span><?php endif;?></div><label class="admin-switch" for="activo"><input id="activo" name="activo" type="checkbox" value="1" <?=$values['activo']?'checked':''?> <?=$isSelf?'disabled':''?>><span class="admin-switch__track" aria-hidden="true"></span><span class="admin-switch__label">Acceso habilitado</span></label><?php if($isSelf):?><input type="hidden" name="activo" value="1"><?php endif;?></div>
</div><footer><a class="admin-button" href="<?=escape(appUrl('admin/usuarios/index.php'))?>">Cancelar</a><button class="admin-button admin-button--primary" type="submit"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Guardar cambios</button></footer></section></form></div></main><?php require dirname(__DIR__,2).'/shared/admin-footer.php';?>

