<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/shared/seguridad.php';require_once dirname(__DIR__,2).'/config/database.php';require_once dirname(__DIR__,2).'/shared/funciones-mantenedores.php';require_once dirname(__DIR__,2).'/shared/admin-flash.php';require_once __DIR__.'/includes/funciones-proveedores.php';require_once __DIR__.'/includes/consultas-proveedores.php';requireAuthentication();
$id=idProveedorValido($_GET['id_proveedor']??null);if($id===null){guardarModalAdmin('error','Proveedor inválido','El proveedor indicado no es válido.');header('Location: '.appUrl('admin/proveedores/index.php'));exit;}
try{$pdo=database();$provider=obtenerProveedor($pdo,$id);$products=productosProveedor($pdo,$id);$available=productosDisponiblesProveedor($pdo,$id);}catch(Throwable $e){$reference=registrarExcepcionAdmin('Supplier detail error',$e);guardarModalAdmin('error','No fue posible abrir el proveedor','Intenta nuevamente.',['reference'=>$reference]);header('Location: '.appUrl('admin/proveedores/index.php'));exit;}if($provider===null){guardarModalAdmin('error','Proveedor no encontrado','El proveedor indicado no existe.');header('Location: '.appUrl('admin/proveedores/index.php'));exit;}
$active=booleanoPostgresMantenedor($provider['activo']);$csrfToken=csrfToken();$pageTitle=$provider['nombre'];$activeSection='proveedores';require dirname(__DIR__,2).'/shared/admin-header.php';require dirname(__DIR__,2).'/shared/admin-sidebar.php';?>
<main class="admin-main"><header class="admin-page-header"><div><a class="admin-back-link" href="<?= escape(appUrl('admin/proveedores/index.php')) ?>">← Volver a proveedores</a><h1 class="admin-page-title"><?= escape($provider['nombre']) ?></h1><span class="admin-status-badge <?= $active?'is-active':'is-inactive' ?>"><?= $active?'Activo':'Inactivo' ?></span></div><div class="admin-actions"><a class="admin-button admin-button--primary" href="<?= escape(appUrl('admin/proveedores/editar.php?id_proveedor='.$id)) ?>">Editar</a><form method="post" action="<?= escape(appUrl('admin/proveedores/cambiar-estado.php')) ?>"><input type="hidden" name="csrf_token" value="<?= escape($csrfToken) ?>"><input type="hidden" name="id_proveedor" value="<?= $id ?>"><button class="admin-button"><?= $active?'Desactivar':'Activar' ?></button></form></div></header>
 <div class="admin-provider-detail-grid"><section class="admin-panel"><div class="admin-panel__header"><h2>Datos generales</h2></div><dl class="admin-provider-data"><?php foreach(['Nombre'=>'nombre','Razón social'=>'razon_social','RUT'=>'rut','Giro'=>'giro','Contacto principal'=>'contacto_principal','Teléfono'=>'telefono','Email'=>'email','Dirección'=>'direccion','Comuna'=>'comuna','Región'=>'region','Sitio web'=>'sitio_web','Instagram'=>'instagram'] as $label=>$field):?><div><dt><?= escape($label) ?></dt><dd><?= escape((string)($provider[$field]?:'No informado')) ?></dd></div><?php endforeach;?></dl></section>
 <section class="admin-panel"><div class="admin-panel__header"><h2>Datos comerciales</h2></div><dl class="admin-provider-data"><?php foreach(['Condición de pago'=>'condicion_pago','Plazo de pago'=>'plazo_pago_dias','Método de pago'=>'metodo_pago','Días de despacho'=>'dias_despacho','Contacto ventas'=>'contacto_ventas','Contacto cobranza'=>'contacto_cobranza'] as $label=>$field):?><div><dt><?= escape($label) ?></dt><dd><?= escape((string)($provider[$field]!==null&&$provider[$field]!==''?$provider[$field].($field==='plazo_pago_dias'?' días':''):'No informado')) ?></dd></div><?php endforeach;?><div><dt>Monto mínimo</dt><dd><?= escape(monedaProveedor($provider['monto_minimo_compra'])) ?></dd></div><div><dt>Observaciones</dt><dd><?= nl2br(escape((string)($provider['observaciones']?:'Sin observaciones'))) ?></dd></div></dl></section></div>
 <section class="admin-panel"><div class="admin-panel__header"><h2>Productos asociados</h2><p>SKU y precio de compra son opcionales.</p></div><?php if($available!==[]):?><form class="admin-provider-association" method="post" action="<?= escape(appUrl('admin/proveedores/guardar-producto.php')) ?>"><input type="hidden" name="csrf_token" value="<?= escape($csrfToken) ?>"><input type="hidden" name="id_proveedor" value="<?= $id ?>"><div class="admin-field"><label for="id_producto">Producto</label><select id="id_producto" name="id_producto" required><option value="">Seleccionar</option><?php foreach($available as $p):?><option value="<?= (int)$p['id_producto'] ?>"><?= escape($p['nombre'].($p['sku']?' · '.$p['sku']:'')) ?></option><?php endforeach;?></select></div><div class="admin-field"><label for="sku_proveedor">SKU proveedor</label><input id="sku_proveedor" name="sku_proveedor" maxlength="80"></div><div class="admin-field"><label for="precio_compra">Precio compra</label><input id="precio_compra" name="precio_compra" type="number" min="0" step="0.01"></div><input type="hidden" name="activo" value="1"><button class="admin-button admin-button--primary">Asociar producto</button></form><?php endif;?>
 <?php if($products!==[]):?><div class="admin-table-wrap"><table class="admin-table admin-provider-products"><thead><tr><th>Producto</th><th>SKU proveedor</th><th>Precio compra</th><th>Estado</th><th>Acción</th></tr></thead><tbody><?php foreach($products as $p):$pa=booleanoPostgresMantenedor($p['activo']);?><tr><td data-label="Producto"><strong><?= escape($p['nombre']) ?></strong><small><?= escape((string)($p['sku']?:'Sin SKU interno')) ?></small></td><td data-label="SKU proveedor"><?= escape((string)($p['sku_proveedor']?:'—')) ?></td><td data-label="Precio"><?= escape(monedaProveedor($p['precio_compra'])) ?></td><td data-label="Estado"><span class="admin-status-badge <?= $pa?'is-active':'is-inactive' ?>"><?= $pa?'Activa':'Inactiva' ?></span></td><td data-label="Acción"><form method="post" action="<?= escape(appUrl('admin/proveedores/cambiar-estado-producto.php')) ?>"><input type="hidden" name="csrf_token" value="<?= escape($csrfToken) ?>"><input type="hidden" name="id_proveedor" value="<?= $id ?>"><input type="hidden" name="id_proveedor_producto" value="<?= (int)$p['id_proveedor_producto'] ?>"><button class="admin-button admin-button--small"><?= $pa?'Desactivar':'Activar' ?></button></form></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="admin-empty-state"><strong>Sin productos asociados</strong><span>Usa el formulario superior para agregar uno.</span></div><?php endif;?></section>
</main><?php require dirname(__DIR__,2).'/shared/admin-footer.php';?>
