<?php
declare(strict_types=1);
require __DIR__ . '/includes/public-page-bootstrap.php';
renderPublicPageStart('Cambios, Devoluciones, Retracto y Garantía Legal | Coratto Pet', 'Política de cambios, devoluciones, retracto y garantía legal de Coratto Pet.', 'legal');
?>
<main id="contenido" class="legal-page"><div class="legal-shell">
    <header class="legal-header"><span>INFORMACIÓN LEGAL</span><h1>Cambios, Devoluciones, Retracto y Garantía Legal</h1><p>Última actualización: agosto de 2026</p></header>
    <article class="legal-document">
        <section><h2>1. Principio general</h2><p>Coratto Pet respeta los derechos establecidos por la Ley N.º 19.496 sobre Protección de los Derechos de los Consumidores.</p><p>Esta política distingue entre:</p><ul><li>derecho a retracto;</li><li>garantía legal;</li><li>productos incorrectos o dañados;</li><li>eventuales beneficios comerciales voluntarios.</li></ul></section>
        <section><h2>2. Derecho a retracto en compras online</h2><p>En las compras realizadas a distancia a través del sitio web, el consumidor podrá ejercer el derecho de retracto en los casos y condiciones establecidos por la legislación vigente.</p><p>Actualmente, el plazo general para ejercerlo es de 10 días contados desde la recepción del producto, siempre que se cumplan los requisitos legales correspondientes.</p><p>Si el proveedor no hubiese enviado la confirmación escrita exigida por la normativa, el plazo puede extenderse conforme a la ley.</p></section>
        <section><h2>3. Condición del producto en caso de retracto</h2><p>Cuando corresponda ejercer retracto respecto de un producto, éste no debe haber sido utilizado más allá de lo necesario para su revisión y deberá conservarse en condiciones compatibles con el ejercicio del derecho conforme a la legislación aplicable.</p><p>El consumidor deberá devolver los elementos, accesorios y componentes que correspondan al producto adquirido.</p></section>
        <section><h2>4. Excepciones al retracto</h2><p>El derecho a retracto puede encontrarse limitado o excluido respecto de determinados bienes en los casos expresamente contemplados por la legislación y reglamentación vigente.</p><p>Coratto Pet no aplicará exclusiones distintas de aquellas autorizadas legalmente y, cuando una exclusión resulte aplicable a un producto, se informará al consumidor de forma clara antes de finalizar la compra.</p></section>
        <section><h2>5. Garantía legal</h2><p>Si un producto nuevo presenta defectos, fallas o no resulta apto para el uso al que normalmente está destinado por causas cubiertas por la ley, el consumidor cuenta con garantía legal durante seis meses desde la recepción del producto.</p><p>En los casos legalmente procedentes, el consumidor podrá optar por las alternativas que reconoce la ley, tales como:</p><ul><li>reparación gratuita;</li><li>cambio del producto; o</li><li>devolución del dinero.</li></ul><p>Coratto Pet no condicionará el ejercicio de la garantía legal a garantías voluntarias ofrecidas por fabricantes.</p></section>
        <section><h2>6. Casos que no constituyen falla cubierta</h2><p>La garantía legal no está destinada a cubrir deterioros derivados exclusivamente de:</p><ul><li>uso inadecuado;</li><li>daño provocado por el consumidor;</li><li>desgaste normal;</li><li>utilización contraria a instrucciones razonables del producto.</li></ul><p>La existencia de una de estas circunstancias deberá evaluarse en cada caso y no se presumirá automáticamente.</p></section>
        <section><h2>7. Producto distinto, incompleto o dañado en transporte</h2><p>Si el cliente recibe:</p><ul><li>un producto distinto del comprado;</li><li>una cantidad incorrecta;</li><li>un producto incompleto; o</li><li>un producto con daño atribuible al transporte o preparación,</li></ul><p>debe comunicarse con Coratto Pet para gestionar una solución.</p><p>Se recomienda acompañar fotografías cuando puedan ayudar a verificar rápidamente la incidencia, sin que ello elimine derechos legales del consumidor.</p></section>
        <section><h2>8. Cómo solicitar retracto, devolución o garantía</h2><p>El cliente puede contactarnos mediante:</p><p>Correo: corattopet@gmail.com<br>WhatsApp: +56 9 6229 1562</p><p>Idealmente indicando:</p><ul><li>nombre;</li><li>número o código del pedido;</li><li>producto involucrado;</li><li>motivo de la solicitud;</li><li>fotografías cuando exista una falla o daño visible.</li></ul><p>Coratto Pet revisará la solicitud y entregará instrucciones para continuar con el procedimiento correspondiente.</p></section>
        <section><h2>9. Devolución de dinero</h2><p>Cuando corresponda legalmente una devolución de dinero, ésta se gestionará mediante un mecanismo compatible con el medio de pago utilizado o mediante otra modalidad acordada con el consumidor.</p><p>Los tiempos efectivos de reflejo bancario pueden depender de entidades financieras o procesadores de pago externos.</p></section>
        <section><h2>10. Cambios voluntarios por gusto, talla o color</h2><p>Coratto Pet no establece por esta política una garantía voluntaria general adicional para cambios por gusto, talla o color.</p><p>Sin perjuicio de ello, el consumidor conserva íntegramente los derechos de retracto y garantía legal que le correspondan.</p><p>Coratto Pet podrá evaluar solicitudes comerciales adicionales caso a caso sin que ello implique crear una obligación permanente para compras futuras.</p></section>
        <section><h2>11. Derechos irrenunciables</h2><p>Ninguna disposición de esta política pretende excluir, restringir o modificar derechos que la legislación reconoce de manera irrenunciable al consumidor.</p></section>
    </article>
</div></main>
<?php renderPublicPageEnd(); ?>
