<?php
declare(strict_types=1);
require __DIR__ . '/includes/public-page-bootstrap.php';
renderPublicPageStart('Política de Despachos y Retiro en Tienda | Coratto Pet', 'Condiciones de despacho y retiro en tienda de las compras realizadas en Coratto Pet.', 'legal');
?>
<main id="contenido" class="legal-page"><div class="legal-shell">
    <header class="legal-header"><span>INFORMACIÓN LEGAL</span><h1>Política de Despachos y Retiro en Tienda</h1><p>Última actualización: agosto de 2026</p></header>
    <article class="legal-document">
        <section><h2>1. Modalidades de entrega</h2><p>Según la disponibilidad y configuración vigente de la tienda, Coratto Pet podrá ofrecer:</p><ul><li>despacho a domicilio; y/o</li><li>retiro en tienda.</li></ul><p>Las alternativas disponibles para cada compra se mostrarán antes del pago.</p></section>
        <section><h2>2. Costo de despacho</h2><p>Cuando una compra incluya despacho, el costo será calculado e informado antes de confirmar el pago.</p><p>El costo podrá depender de factores como destino, comuna, peso estimado de los productos y condiciones de la modalidad seleccionada.</p><p>El cliente podrá revisar el subtotal, costo de despacho y total antes de efectuar el pago.</p></section>
        <section><h2>3. Cobertura</h2><p>Coratto Pet realizará despachos únicamente a las comunas y regiones que se encuentren habilitadas en la plataforma al momento de efectuar la compra.</p><p>Si una dirección se encuentra fuera de cobertura, el sistema podrá impedir seleccionar despacho para dicha ubicación.</p></section>
        <section><h2>4. Preparación de pedidos con despacho</h2><p>Los pedidos con despacho requieren un plazo mínimo de 24 horas hábiles para su preparación y gestión.</p><p>Este plazo corresponde a preparación y procesamiento y no constituye una promesa de entrega en 24 horas.</p><p>El tiempo total hasta la recepción puede variar según:</p><ul><li>comuna o región de destino;</li><li>horario y día en que se realizó la compra;</li><li>disponibilidad efectiva;</li><li>empresa transportista;</li><li>contingencias logísticas;</li><li>fines de semana o días festivos;</li><li>circunstancias excepcionales ajenas al control razonable de Coratto Pet.</li></ul><p>Cuando corresponda, Coratto Pet comunicará información de seguimiento al cliente.</p></section>
        <section><h2>5. Dirección de entrega</h2><p>El cliente debe proporcionar una dirección correcta y suficientemente completa para permitir la entrega.</p><p>Se recomienda revisar especialmente:</p><ul><li>región;</li><li>comuna;</li><li>calle;</li><li>número;</li><li>departamento, oficina o unidad cuando corresponda;</li><li>referencias necesarias;</li><li>teléfono y correo de contacto.</li></ul><p>Si existe un problema con la dirección, Coratto Pet podrá contactar al cliente para solicitar información adicional.</p></section>
        <section><h2>6. Incidencias de entrega</h2><p>Si la entrega no pudiera completarse por ausencia del receptor, información incorrecta u otra circunstancia, Coratto Pet y/o el transportista podrán coordinar nuevas instrucciones.</p><p>Costos adicionales que eventualmente resulten de un nuevo despacho sólo podrán cobrarse cuando correspondan y sean informados al cliente.</p></section>
        <section><h2>7. Productos dañados o pedido incorrecto</h2><p>Si un pedido llega con signos evidentes de daño, contiene un producto distinto al adquirido o presenta una incidencia atribuible al despacho, el cliente deberá contactar a Coratto Pet tan pronto como sea razonablemente posible a:</p><p>WhatsApp: +56 9 6229 1562<br>Correo: corattopet@gmail.com</p><p>Esto no limita los plazos ni derechos legales que correspondan al consumidor.</p></section>
        <section><h2>8. Retiro en tienda</h2><p>Cuando la opción Retiro en tienda se encuentre disponible, el cliente podrá seleccionarla antes de efectuar el pago.</p><p>El hecho de que un producto tenga stock no significa que el pedido pueda retirarse inmediatamente.</p><p>Después de la compra, Coratto Pet deberá preparar el pedido.</p><p>El cliente debe esperar el correo de confirmación que indique que el pedido está listo para retiro antes de acudir al punto de entrega.</p><p>El flujo habitual será:</p><p>Pedido recibido → En preparación → Listo para retiro → Entregado</p></section>
        <section><h2>9. Horarios de retiro</h2><p>Los horarios publicados corresponden a períodos en los que puede realizarse el retiro una vez que el pedido haya sido confirmado como listo.</p><p>No representan una garantía de disponibilidad inmediata después de efectuar la compra.</p></section>
        <section><h2>10. Entrega del pedido retirado</h2><p>Coratto Pet podrá solicitar información que permita identificar correctamente el pedido antes de realizar la entrega.</p></section>
        <section><h2>11. Información previa a la compra</h2><p>La modalidad de entrega, disponibilidad, costo de despacho y demás condiciones relevantes se informan antes de la contratación conforme a las obligaciones aplicables al comercio electrónico.</p></section>
    </article>
</div></main>
<?php renderPublicPageEnd(); ?>
