<?php
declare(strict_types=1);
require __DIR__ . '/includes/public-page-bootstrap.php';
renderPublicPageStart('Política de Privacidad y Datos Personales | Coratto Pet', 'Política de privacidad y tratamiento de datos personales de Coratto Pet.', 'legal');
?>
<main id="contenido" class="legal-page"><div class="legal-shell">
    <header class="legal-header"><span>INFORMACIÓN LEGAL</span><h1>Política de Privacidad y Datos Personales</h1><p>Última actualización: agosto de 2026</p></header>
    <article class="legal-document">
        <section><h2>1. Responsable</h2><p>El responsable del tratamiento de los datos recopilados a través de Coratto Pet es:</p><p>CORATTO PET SpA<br>RUT 78.443.512-1<br>Correo: corattopet@gmail.com<br>WhatsApp: +56 9 6229 1562<br>Chillán, Región de Ñuble, Chile.</p></section>
        <section><h2>2. Datos que podemos recopilar</h2><p>Según la forma en que utilices el sitio, Coratto Pet puede tratar información como:</p><ul><li>nombre y apellidos;</li><li>correo electrónico;</li><li>teléfono;</li><li>dirección y comuna;</li><li>datos necesarios para la gestión y entrega de pedidos;</li><li>información asociada a tu cuenta;</li><li>historial de pedidos y estados de compra;</li><li>mensajes enviados mediante formularios de contacto;</li><li>preferencias o antecedentes proporcionados voluntariamente en herramientas de orientación nutricional;</li><li>información técnica necesaria para el funcionamiento y seguridad del sitio.</li></ul><p>Coratto Pet no necesita conocer ni almacenar los datos completos de tarjetas utilizados en plataformas externas de pago.</p></section>
        <section><h2>3. Finalidades</h2><p>Los datos podrán utilizarse para:</p><ul><li>registrar y administrar cuentas;</li><li>procesar compras;</li><li>gestionar pagos y confirmar pedidos;</li><li>coordinar despacho o retiro;</li><li>enviar información relacionada con el estado de una compra;</li><li>responder consultas y solicitudes;</li><li>gestionar recuperación y seguridad de cuentas;</li><li>generar pautas o resultados cuando el usuario utilice herramientas personalizadas del sitio;</li><li>cumplir obligaciones legales y tributarias;</li><li>prevenir fraude, abuso o incidentes de seguridad;</li><li>mejorar el funcionamiento de la plataforma.</li></ul><p>No utilizaremos datos recopilados para una finalidad incompatible con aquella para la cual fueron obtenidos sin contar con fundamento suficiente o consentimiento cuando éste corresponda.</p></section>
        <section><h2>4. Información nutricional ingresada por el usuario</h2><p>Las herramientas nutricionales disponibles en Coratto Pet tienen carácter orientativo.</p><p>La información que el usuario ingrese voluntariamente sobre su mascota podrá utilizarse para calcular recomendaciones estimadas y generar fichas o pautas solicitadas por el propio usuario.</p><p>Estas herramientas no reemplazan el diagnóstico ni la evaluación de un médico veterinario.</p></section>
        <section><h2>5. Comunicación a terceros</h2><p>Coratto Pet podrá comunicar o permitir el tratamiento de datos por proveedores cuando sea necesario para prestar el servicio, por ejemplo:</p><ul><li>proveedores de hosting e infraestructura;</li><li>servicios de correo electrónico;</li><li>procesadores de pago;</li><li>empresas de transporte o despacho;</li><li>servicios técnicos necesarios para seguridad y funcionamiento de la plataforma.</li></ul><p>Sólo se proporcionará la información necesaria para cumplir la finalidad correspondiente.</p><p>Coratto Pet no vende bases de datos personales a terceros.</p></section>
        <section><h2>6. Conservación</h2><p>Los datos serán conservados durante el tiempo necesario para cumplir las finalidades para las que fueron recopilados y las obligaciones legales, tributarias, contractuales o de respaldo que resulten aplicables.</p><p>Cuando la información deje de ser necesaria y no exista obligación de conservarla, podrá ser eliminada, anonimizada o bloqueada conforme corresponda.</p></section>
        <section><h2>7. Seguridad</h2><p>Coratto Pet adopta medidas técnicas y organizativas razonables destinadas a proteger la información contra pérdida, acceso no autorizado, alteración o divulgación indebida.</p><p>No obstante, ningún sistema conectado a Internet puede garantizar seguridad absoluta.</p></section>
        <section><h2>8. Derechos de las personas</h2><p>Las personas podrán ejercer los derechos que les reconoce la legislación vigente respecto de sus datos personales, incluyendo solicitar información sobre su tratamiento y, cuando corresponda, rectificación, eliminación, oposición u otros derechos establecidos legalmente.</p><p>Las solicitudes podrán enviarse a:</p><p>corattopet@gmail.com</p><p>Coratto Pet podrá solicitar información razonable para verificar la identidad de quien formula la solicitud antes de entregar o modificar datos personales.</p></section>
        <section><h2>9. Cookies e información técnica</h2><p>El sitio podrá utilizar almacenamiento local, sesiones, cookies u otros mecanismos estrictamente necesarios para funciones tales como:</p><ul><li>mantener una sesión iniciada;</li><li>conservar el carrito;</li><li>proteger formularios;</li><li>mantener configuraciones temporales;</li><li>procesar funciones necesarias para la experiencia del usuario.</li></ul><p>Si posteriormente Coratto Pet incorpora herramientas de analítica, marketing o publicidad que utilicen tecnologías adicionales de seguimiento, esta política deberá actualizarse y se implementarán los mecanismos de información o consentimiento que correspondan.</p></section>
        <section><h2>10. Menores de edad</h2><p>La tienda no está dirigida específicamente a menores de edad.</p><p>Cuando una compra requiera capacidad legal para contratar, deberá ser realizada por una persona habilitada para ello o bajo la responsabilidad de su representante legal.</p></section>
        <section><h2>11. Cambios normativos</h2><p>Actualmente el tratamiento de datos personales en Chile se encuentra regulado principalmente por la Ley N.º 19.628. La Ley N.º 21.719 introduce un nuevo régimen de protección de datos personales y entra en vigencia el 1 de diciembre de 2026. Coratto Pet procurará adaptar sus procedimientos a las obligaciones que resulten aplicables.</p></section>
    </article>
</div></main>
<?php renderPublicPageEnd(); ?>
