<?php
declare(strict_types=1);
require __DIR__ . '/includes/public-page-bootstrap.php';
renderPublicPageStart('Términos y Condiciones de Compra | Coratto Pet', 'Términos y condiciones aplicables a las compras realizadas en Coratto Pet.', 'legal');
?>
<main id="contenido" class="legal-page"><div class="legal-shell">
    <header class="legal-header"><span>INFORMACIÓN LEGAL</span><h1>Términos y Condiciones de Compra</h1><p>Última actualización: agosto de 2026</p></header>
    <article class="legal-document">
        <section><h2>1. Identificación del proveedor</h2><p>El presente sitio web y tienda en línea son operados por CORATTO PET SpA, RUT 78.443.512-1, dedicada a la comercialización e importación de productos para mascotas y a la venta al por menor de alimentos y accesorios para mascotas.</p><p>Para consultas relacionadas con compras, productos o atención al cliente, puedes contactarnos a través de:</p><p>Correo electrónico: corattopet@gmail.com<br>WhatsApp: +56 9 6229 1562<br>Ubicación: Chillán, Región de Ñuble, Chile.</p></section>
        <section><h2>2. Alcance</h2><p>Estos Términos y Condiciones regulan el uso de la tienda online de Coratto Pet y las compras realizadas a través de ella.</p><p>Al efectuar una compra, el cliente declara haber tenido acceso a la información esencial del producto, su precio, disponibilidad, modalidad de entrega, costos asociados y demás condiciones aplicables antes de efectuar el pago.</p><p>Los derechos reconocidos por la legislación chilena de protección al consumidor no se ven limitados por estas condiciones.</p></section>
        <section><h2>3. Información de los productos</h2><p>Coratto Pet procura mantener actualizada la información relativa a nombres, marcas, presentaciones, características, fotografías, disponibilidad y precios.</p><p>Las fotografías son referenciales y pueden existir diferencias menores derivadas de cambios de envase, presentación, tonalidad o actualización realizada por el fabricante que no alteren las características esenciales del producto.</p><p>Cuando un producto se ofrece en distintas presentaciones, tamaños o formatos, el precio aplicable será el informado para la alternativa seleccionada antes de confirmar la compra.</p></section>
        <section><h2>4. Precios</h2><p>Los precios publicados se expresan en pesos chilenos y corresponden al precio vigente al momento de efectuar la compra.</p><p>Cuando el catálogo indique un precio “desde”, éste corresponde al menor precio disponible entre las presentaciones publicadas para dicho producto. Antes del pago, el cliente podrá visualizar el precio específico de la alternativa seleccionada.</p><p>El costo de despacho, cuando corresponda, se informa separadamente antes de efectuar el pago y se incorpora al total de la compra.</p></section>
        <section><h2>5. Disponibilidad y stock</h2><p>La publicación de un producto no garantiza disponibilidad indefinida.</p><p>La compra queda sujeta a la disponibilidad efectiva del producto al momento de procesar el pedido. Coratto Pet utiliza mecanismos de control y reserva de stock durante el proceso de compra.</p><p>Si excepcionalmente se detectara una imposibilidad de cumplir un pedido ya pagado, Coratto Pet contactará al cliente para ofrecer las alternativas que correspondan, incluida la restitución de las sumas pagadas cuando proceda.</p></section>
        <section><h2>6. Proceso de compra</h2><p>Para realizar una compra, el cliente deberá:</p><ul><li>seleccionar el producto y, cuando corresponda, su presentación;</li><li>indicar la cantidad;</li><li>incorporar el producto al carrito;</li><li>ingresar o confirmar sus datos de contacto y entrega;</li><li>seleccionar una modalidad de entrega;</li><li>revisar el subtotal, costo de despacho y total;</li><li>seleccionar el medio de pago disponible; y</li><li>confirmar la operación.</li></ul><p>La compra se entenderá perfeccionada una vez que el pago sea autorizado y el pedido sea confirmado por Coratto Pet.</p><p>El cliente recibirá una confirmación por los medios de contacto registrados durante la compra.</p></section>
        <section><h2>7. Medios de pago</h2><p>Los medios de pago habilitados serán informados durante el proceso de checkout.</p><p>Cuando el pago sea procesado mediante plataformas de terceros, como Transbank, el cliente será redirigido al entorno correspondiente para completar la operación.</p><p>Coratto Pet no almacena números completos de tarjetas bancarias ni credenciales bancarias ingresadas directamente en las plataformas de pago externas.</p></section>
        <section><h2>8. Datos proporcionados por el cliente</h2><p>El cliente es responsable de ingresar información completa y correcta, especialmente nombre, correo electrónico, teléfono, comuna y dirección de entrega.</p><p>Coratto Pet no será responsable por retrasos o problemas de entrega derivados exclusivamente de datos incorrectos o incompletos proporcionados por el cliente, sin perjuicio de que procurará contactar al comprador para resolver la incidencia.</p></section>
        <section><h2>9. Despacho y retiro</h2><p>Las condiciones particulares de entrega se encuentran disponibles en la <a href="<?= e(appUrl('public/politicas-envio.php')) ?>">Política de Despachos y Retiro en Tienda</a>.</p><p>El costo y modalidad de entrega aplicables serán informados antes de efectuar el pago.</p></section>
        <section><h2>10. Cambios, retracto y garantía legal</h2><p>Los derechos relacionados con retracto, productos defectuosos, devoluciones y garantía legal se regulan en la sección <a href="<?= e(appUrl('public/cambios-devoluciones.php')) ?>">Cambios, Devoluciones, Retracto y Garantía Legal</a> y por la normativa chilena vigente.</p><p>Estas condiciones no limitan ni excluyen derechos irrenunciables del consumidor.</p></section>
        <section><h2>11. Promociones y descuentos</h2><p>Las promociones podrán estar sujetas a condiciones particulares, tales como plazo, stock disponible, productos seleccionados o mecanismos específicos de aplicación.</p><p>Las condiciones relevantes serán informadas junto con la promoción.</p></section>
        <section><h2>12. Errores evidentes de publicación</h2><p>Coratto Pet procura evitar errores en la publicación de precios y características.</p><p>Si se detecta un error manifiesto o evidente antes de completar una compra, será corregido tan pronto sea posible.</p><p>Si se detecta después de realizada una operación, Coratto Pet contactará al cliente y actuará conforme a la legislación aplicable, sin utilizar esta disposición para desconocer derechos legalmente adquiridos por consumidores.</p></section>
        <section><h2>13. Uso del sitio</h2><p>El usuario se compromete a utilizar el sitio de manera lícita y a no realizar acciones destinadas a interferir con su funcionamiento, vulnerar medidas de seguridad, acceder sin autorización a sistemas o utilizar información del sitio con fines ilícitos.</p></section>
        <section><h2>14. Propiedad intelectual</h2><p>Los elementos gráficos, marcas, diseños, fotografías propias, textos y demás contenidos originales de Coratto Pet están protegidos conforme a la legislación aplicable.</p><p>Las marcas, fotografías o contenidos pertenecientes a fabricantes o terceros pertenecen a sus respectivos titulares.</p></section>
        <section><h2>15. Modificaciones</h2><p>Coratto Pet podrá actualizar estos términos cuando resulte necesario por cambios en sus servicios, funcionamiento o normativa.</p><p>Las modificaciones no afectarán retroactivamente derechos derivados de compras celebradas bajo condiciones anteriores.</p></section>
        <section><h2>16. Legislación aplicable</h2><p>Las relaciones entre Coratto Pet y sus consumidores se rigen por las leyes de la República de Chile, particularmente la Ley N.º 19.496 sobre Protección de los Derechos de los Consumidores y la normativa complementaria aplicable.</p></section>
    </article>
</div></main>
<?php renderPublicPageEnd(); ?>
