<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/shared/seguridad.php'; require_once dirname(__DIR__,2).'/config/database.php'; require_once dirname(__DIR__,2).'/shared/funciones-mantenedores.php';
require_once __DIR__.'/includes/funciones-clientes.php'; require_once __DIR__.'/includes/validaciones-clientes.php'; require_once __DIR__.'/includes/consultas-clientes.php';
requireAuthentication(); $filters=normalizarFiltrosClientes($_GET); $summary=['registrados'=>0,'con_pedidos'=>0,'nuevos_mes'=>0,'pedidos_asociados'=>0,'total_vendido'=>0]; $clients=[]; $total=0; $databaseError=false;
try{$pdo=database();$total=contarClientes($pdo,$filters);$pages=max(1,(int)ceil($total/$filters['por_pagina']));$filters['pagina']=min($filters['pagina'],$pages);$clients=obtenerClientes($pdo,$filters,$filters['pagina'],$filters['por_pagina']);$summary=obtenerResumenClientes($pdo);}catch(Throwable $e){$databaseError=true;$pages=1;$ref=registrarExcepcionAdmin('Customers listing error',$e);$adminModal=['type'=>'error','title'=>'No fue posible cargar los clientes','message'=>'No se pudo completar la acción.','reference'=>$ref];}
$hasFilters=array_filter(array_intersect_key($filters,array_flip(['nombre','email','telefono','comuna','region'])),fn($v)=>$v!=='')!==[];$base=array_filter($filters,fn($v,$k)=>!in_array($k,['pagina','por_pagina'],true)&&$v!=='',ARRAY_FILTER_USE_BOTH);$pageUrl=fn(int $p)=>appUrl('admin/clientes/index.php').'?'.http_build_query(array_merge($base,['pagina'=>$p]));
$pageTitle='Clientes';$activeSection='clientes';$csrfToken=csrfToken();require dirname(__DIR__,2).'/shared/admin-header.php';require dirname(__DIR__,2).'/shared/admin-sidebar.php';?>
<main class="admin-main" id="contenido-principal"><header class="admin-page-header admin-customers-heading"><div><span>Relaciones comerciales</span><h1 class="admin-page-title admin-page-title--paw">Clientes</h1><p>Consulta clientes, datos de contacto e historial de compras.</p></div></header>
<section class="admin-customer-summary" aria-label="Resumen de clientes"><?php foreach([['registrados','Clientes registrados'],['con_pedidos','Clientes con pedidos'],['nuevos_mes','Nuevos este mes'],['pedidos_asociados','Pedidos asociados']] as [$k,$l]):?><article><span><?=escape($l)?></span><strong><?=escape(number_format((int)$summary[$k],0,',','.'))?></strong></article><?php endforeach;?><article class="admin-customer-summary__sales"><span>Total vendido</span><strong><?=escape(formatearDineroCliente($summary['total_vendido']))?></strong></article></section>
<section class="admin-customer-panel"><header><div><span>Directorio comercial</span><h2>Listado de clientes</h2></div><strong><?=escape((string)$total)?> registros</strong></header><form class="admin-customer-filters" method="get"><div class="admin-field"><label for="nombre">Nombre</label><input id="nombre" name="nombre" value="<?=escape($filters['nombre'])?>"></div><div class="admin-field"><label for="email">Email</label><input id="email" name="email" type="search" value="<?=escape($filters['email'])?>"></div><div class="admin-field"><label for="telefono">Teléfono</label><input id="telefono" name="telefono" value="<?=escape($filters['telefono'])?>"></div><div class="admin-field"><label for="comuna">Comuna</label><input id="comuna" name="comuna" value="<?=escape($filters['comuna'])?>"></div><div class="admin-field"><label for="region">Región</label><input id="region" name="region" value="<?=escape($filters['region'])?>"></div><div><button class="admin-button admin-button--primary">Buscar</button><?php if($hasFilters):?><a class="admin-button" href="<?=escape(appUrl('admin/clientes/index.php'))?>">Limpiar</a><?php endif;?></div></form>
<?php if($clients!==[]):?><div class="admin-customer-table-wrap"><table class="admin-data-table admin-customer-table"><thead><tr><th>Cliente</th><th>Contacto</th><th>Ubicación</th><th>Pedidos</th><th>Total comprado</th><th>Última compra</th><th></th></tr></thead><tbody><?php foreach($clients as $client):?><tr><td data-label="Cliente"><strong><?=escape((string)$client['nombre'])?></strong><small><?=escape((string)($client['rut']?:'Sin RUT'))?></small></td><td data-label="Contacto"><span><?=escape((string)($client['email']?:'Sin email'))?></span><small><?=escape((string)($client['telefono']?:'Sin teléfono'))?></small></td><td data-label="Ubicación"><span><?=escape((string)($client['comuna']?:'Sin comuna'))?></span><small><?=escape((string)($client['region']?:'Sin región'))?></small></td><td data-label="Pedidos"><strong><?=escape((string)$client['cantidad_pedidos'])?></strong></td><td data-label="Total"><strong class="admin-customer-money"><?=escape(formatearDineroCliente($client['total_comprado']))?></strong></td><td data-label="Última compra"><?=escape(formatearFechaCliente($client['ultima_compra'],'d-m-Y'))?></td><td><a class="admin-order-view" href="<?=escape(appUrl('admin/clientes/ver.php?id_cliente='.$client['id_cliente']))?>">Ver detalle →</a></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="admin-customer-empty"><span>CP</span><h3><?=$databaseError?'No fue posible cargar los clientes':($hasFilters?'No encontramos clientes':'Aún no hay clientes registrados')?></h3><p><?=$hasFilters?'Prueba con otros criterios o limpia los filtros.':'Los clientes aparecerán aquí cuando sean asociados a pedidos.'?></p></div><?php endif;?>
<?php if($pages>1):?><nav class="admin-order-pagination"><?php if($filters['pagina']>1):?><a href="<?=escape($pageUrl($filters['pagina']-1))?>">← Anterior</a><?php endif;?><span>Página <?=escape((string)$filters['pagina'])?> de <?=escape((string)$pages)?></span><?php if($filters['pagina']<$pages):?><a href="<?=escape($pageUrl($filters['pagina']+1))?>">Siguiente →</a><?php endif;?></nav><?php endif;?></section></main><?php require dirname(__DIR__,2).'/shared/admin-footer.php';?>
