BEGIN;

CREATE TABLE IF NOT EXISTS importaciones (
    id_importacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NULL REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'cargado',
    total_filas INTEGER NOT NULL DEFAULT 0 CHECK (total_filas >= 0),
    productos_creados INTEGER NOT NULL DEFAULT 0 CHECK (productos_creados >= 0),
    productos_actualizados INTEGER NOT NULL DEFAULT 0 CHECK (productos_actualizados >= 0),
    filas_con_error INTEGER NOT NULL DEFAULT 0 CHECK (filas_con_error >= 0),
    resumen_errores JSONB NOT NULL DEFAULT '[]'::jsonb,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finalizado_en TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_importaciones_creado_en
    ON importaciones (creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_importaciones_estado
    ON importaciones (estado);

COMMIT;
