<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/shared/seguridad.php';
require_once dirname(__DIR__, 2) . '/config/database.php';
require_once dirname(__DIR__, 2) . '/shared/funciones-mantenedores.php';
require_once dirname(__DIR__, 2) . '/shared/admin-flash.php';
require_once __DIR__ . '/includes/funciones-pedidos.php';
require_once __DIR__ . '/includes/validaciones-pedidos.php';
require_once __DIR__ . '/includes/consultas-pedidos.php';

requireAuthentication();
$orderId = idPedidoValido($_GET['id_pedido'] ?? null);
if ($orderId === null) { guardarModalAdmin('error', 'No fue posible abrir el pedido', 'El pedido indicado no es válido.'); header('Location: ' . appUrl('admin/pedidos/index.php'), true, 302); exit; }
try { $connection = database(); $order = obtenerPedido($connection, $orderId); $details = obtenerDetallesPedido($connection, $orderId); $history = obtenerHistorialPedido($connection, $orderId); }
catch (Throwable $exception) { $reference = registrarExcepcionAdmin('Order detail error', $exception); guardarModalAdmin('error', 'No fue posible abrir el pedido', 'No se pudo completar la acción.', ['reference' => $reference]); header('Location: ' . appUrl('admin/pedidos/index.php'), true, 302); exit; }
if ($order === null) { guardarModalAdmin('error', 'No fue posible abrir el pedido', 'El pedido indicado no existe.'); header('Location: ' . appUrl('admin/pedidos/index.php'), true, 302); exit; }

$state = consumirEstadoMantenedor('pedido_estado_' . $orderId);
$formValues = ['estado' => (string) $order['estado'], 'estado_pago' => (string) $order['estado_pago'], 'observaciones_internas' => (string) ($order['observaciones_internas'] ?? '')];
if (is_array($state['valores'] ?? null)) { $formValues = array_merge($formValues, array_intersect_key($state['valores'], $formValues)); }
$errors = is_array($state['errores'] ?? null) ? $state['errores'] : [];
$generalError = is_string($state['error_general'] ?? null) ? $state['error_general'] : null;
if ($errors !== [] || $generalError !== null) { $adminModal = ['type' => 'error', 'title' => 'No fue posible actualizar el pedido', 'message' => $errors !== [] ? 'Revisa los campos marcados antes de continuar.' : 'No se pudo completar la acción.', 'detail' => resumenErroresFormulario($errors, $generalError), 'reference' => (string) ($state['referencia'] ?? ''), 'primaryText' => 'Aceptar']; }

$pageTitle = 'Pedido ' . $order['codigo_pedido']; $activeSection = 'pedidos'; $csrfToken = csrfToken();
require dirname(__DIR__, 2) . '/shared/admin-header.php'; require dirname(__DIR__, 2) . '/shared/admin-sidebar.php';
?>
<main class="admin-main" id="contenido-principal">
    <header class="admin-page-header admin-order-detail-heading"><div><a class="admin-back-link" href="<?= escape(appUrl('admin/pedidos/index.php')) ?>">← Volver a pedidos</a><span class="admin-orders-eyebrow">Detalle de compra</span><h1 class="admin-page-title"><?= escape((string) $order['codigo_pedido']) ?></h1><p>Revisa la información del cliente, la entrega y el avance del pedido.</p></div></header>
    <section class="admin-order-identity" aria-label="Resumen del pedido"><div><span>Pedido</span><strong><?= escape((string) $order['codigo_pedido']) ?></strong><time><?= escape(formatearFechaPedido($order['creado_en'])) ?></time></div><dl><div><dt>Estado</dt><dd><span class="admin-order-badge <?= escape(claseEstadoPedido((string) $order['estado'])) ?>"><?= escape(etiquetaEstadoPedido((string) $order['estado'])) ?></span></dd></div><div><dt>Pago</dt><dd><span class="admin-order-badge <?= escape(claseEstadoPedido((string) $order['estado_pago'], true)) ?>"><?= escape(etiquetaEstadoPagoPedido((string) $order['estado_pago'])) ?></span></dd></div><div><dt>Total</dt><dd class="admin-order-identity__total"><?= escape(formatearDineroPedido($order['total'])) ?></dd></div></dl></section>
    <div class="admin-order-detail-grid">
        <div class="admin-order-detail-main">
            <section class="admin-order-card admin-order-info-panel"><header><span>01</span><div><h2>Información del pedido</h2><p>Datos del cliente y detalles de entrega asociados a esta compra.</p></div></header><div class="admin-order-info-grid"><section class="admin-order-info-block" aria-labelledby="customer-info-title"><h3 id="customer-info-title">Datos del cliente</h3><dl class="admin-order-detail-list"><div><dt>Nombre</dt><dd><?= escape((string) ($order['cliente_nombre'] ?: 'Cliente no asociado')) ?></dd></div><div><dt>Email</dt><dd><?= escape((string) ($order['cliente_email'] ?: 'No informado')) ?></dd></div><div><dt>Teléfono</dt><dd><?= escape((string) ($order['cliente_telefono'] ?: 'No informado')) ?></dd></div><div><dt>RUT</dt><dd><?= escape((string) ($order['cliente_rut'] ?: 'No informado')) ?></dd></div></dl></section><section class="admin-order-info-block" aria-labelledby="delivery-info-title"><h3 id="delivery-info-title">Datos de entrega</h3><dl class="admin-order-detail-list"><div><dt>Método</dt><dd><?= escape(descripcionEntregaPedido($order['metodo_entrega'])) ?></dd></div><div><dt>Dirección</dt><dd><?= escape((string) ($order['direccion_entrega'] ?: $order['cliente_direccion'] ?: 'No informada')) ?></dd></div><div><dt>Comuna</dt><dd><?= escape((string) ($order['comuna_entrega'] ?: $order['cliente_comuna'] ?: 'No informada')) ?></dd></div><div><dt>Región</dt><dd><?= escape((string) ($order['region_entrega'] ?: $order['cliente_region'] ?: 'No informada')) ?></dd></div><?php if (!empty($order['observaciones_cliente'])): ?><div class="admin-order-detail-list__note"><dt>Observación</dt><dd><?= nl2br(escape((string) $order['observaciones_cliente'])) ?></dd></div><?php endif; ?></dl></section></div></section>
            <section class="admin-order-card admin-order-products"><header><span>02</span><div><h2>Productos</h2><p>Snapshot de los artículos incluidos en la compra.</p></div></header><?php if ($details !== []): ?><div class="admin-order-products__wrap"><table class="admin-data-table"><thead><tr><th>Producto</th><th>SKU</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody><?php foreach ($details as $item): ?><tr><td data-label="Producto"><strong><?= escape((string) $item['nombre_producto']) ?></strong><?php if ($item['tipo_item'] === 'presentacion'): ?><small><?= escape((string) ($item['presentacion_nombre'] ?: (($item['cantidad_gramos'] ?? null) ? $item['cantidad_gramos'] . ' g' : 'Presentación'))) ?></small><?php endif; ?></td><td data-label="SKU"><?= escape((string) ($item['sku'] ?: 'Sin SKU')) ?></td><td data-label="Cantidad"><?= escape((string) $item['cantidad']) ?><?= $item['tipo_item'] === 'presentacion' && $item['cantidad_gramos'] ? ' × ' . escape((string) $item['cantidad_gramos']) . ' g' : '' ?></td><td data-label="Precio"><?= escape(formatearDineroPedido($item['precio_unitario'])) ?></td><td data-label="Subtotal"><strong><?= escape(formatearDineroPedido($item['subtotal'])) ?></strong></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p class="admin-order-inline-empty">Este pedido todavía no tiene productos asociados.</p><?php endif; ?></section>
            <section class="admin-order-card"><header><span>03</span><div><h2>Historial</h2><p>Trazabilidad de los cambios administrativos.</p></div></header><?php if ($history !== []): ?><ol class="admin-order-history"><?php foreach ($history as $event): ?><li><span class="admin-order-history__dot"></span><div><header><strong><?= escape((string) ($event['usuario_nombre'] ?: 'Usuario no disponible')) ?></strong><time><?= escape(formatearFechaPedido($event['creado_en'])) ?></time></header><?php if ($event['estado_nuevo'] !== null): ?><p>Estado: <span><?= escape(etiquetaEstadoPedido((string) $event['estado_anterior'])) ?></span> → <strong><?= escape(etiquetaEstadoPedido((string) $event['estado_nuevo'])) ?></strong></p><?php endif; ?><?php if ($event['estado_pago_nuevo'] !== null): ?><p>Pago: <span><?= escape(etiquetaEstadoPagoPedido((string) $event['estado_pago_anterior'])) ?></span> → <strong><?= escape(etiquetaEstadoPagoPedido((string) $event['estado_pago_nuevo'])) ?></strong></p><?php endif; ?><?php if (!empty($event['observacion'])): ?><small><?= nl2br(escape((string) $event['observacion'])) ?></small><?php endif; ?></div></li><?php endforeach; ?></ol><?php else: ?><p class="admin-order-inline-empty">Aún no hay cambios registrados para este pedido.</p><?php endif; ?></section>
        </div>
        <aside class="admin-order-detail-side">
            <section class="admin-order-card admin-order-totals"><header><span>04</span><div><h2>Totales</h2></div></header><dl><div><dt>Subtotal</dt><dd><?= escape(formatearDineroPedido($order['subtotal'])) ?></dd></div><div><dt>Descuento</dt><dd>− <?= escape(formatearDineroPedido($order['descuento'])) ?></dd></div><div><dt>Despacho</dt><dd><?= escape(formatearDineroPedido($order['costo_despacho'])) ?></dd></div><div class="admin-order-totals__final"><dt>Total</dt><dd><?= escape(formatearDineroPedido($order['total'])) ?></dd></div></dl><?php if (!empty($order['metodo_pago']) || !empty($order['referencia_pago'])): ?><p><strong><?= escape((string) ($order['metodo_pago'] ?: 'Método no informado')) ?></strong><?php if (!empty($order['referencia_pago'])): ?><span>Ref. <?= escape((string) $order['referencia_pago']) ?></span><?php endif; ?></p><?php endif; ?></section>
            <section class="admin-order-card admin-order-management"><header><span>05</span><div><h2>Gestión interna</h2><p>Actualiza el avance sin modificar inventario.</p></div></header><form method="post" action="<?= escape(appUrl('admin/pedidos/actualizar-estado.php')) ?>"><input type="hidden" name="csrf_token" value="<?= escape($csrfToken) ?>"><input type="hidden" name="id_pedido" value="<?= escape((string) $orderId) ?>"><div class="admin-field<?= isset($errors['estado']) ? ' admin-field--invalid' : '' ?>"><label for="estado">Estado pedido</label><select id="estado" name="estado"><?php foreach (estadosPedido() as $value => $label): ?><option value="<?= escape($value) ?>" <?= $formValues['estado'] === $value ? 'selected' : '' ?>><?= escape($label) ?></option><?php endforeach; ?></select><?php if (isset($errors['estado'])): ?><span class="admin-field__error"><?= escape((string) $errors['estado']) ?></span><?php endif; ?></div><div class="admin-field<?= isset($errors['estado_pago']) ? ' admin-field--invalid' : '' ?>"><label for="estado_pago">Estado pago</label><select id="estado_pago" name="estado_pago"><?php foreach (estadosPagoPedido() as $value => $label): ?><option value="<?= escape($value) ?>" <?= $formValues['estado_pago'] === $value ? 'selected' : '' ?>><?= escape($label) ?></option><?php endforeach; ?></select><?php if (isset($errors['estado_pago'])): ?><span class="admin-field__error"><?= escape((string) $errors['estado_pago']) ?></span><?php endif; ?></div><div class="admin-field<?= isset($errors['observaciones_internas']) ? ' admin-field--invalid' : '' ?>"><label for="observaciones_internas">Observaciones internas</label><textarea id="observaciones_internas" name="observaciones_internas" maxlength="1000" rows="5" placeholder="Notas visibles solo para administración"><?= escape((string) $formValues['observaciones_internas']) ?></textarea><?php if (isset($errors['observaciones_internas'])): ?><span class="admin-field__error"><?= escape((string) $errors['observaciones_internas']) ?></span><?php endif; ?></div><button class="admin-button admin-button--primary" type="submit">Guardar cambios</button></form></section>
        </aside>
    </div>
</main>
<?php require dirname(__DIR__, 2) . '/shared/admin-footer.php'; ?>
