<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/shared/seguridad.php'; require_once dirname(__DIR__, 2) . '/config/database.php'; require_once dirname(__DIR__, 2) . '/shared/funciones-mantenedores.php'; require_once __DIR__ . '/includes/funciones-marca.php'; require_once __DIR__ . '/includes/validaciones-marca.php'; requireAuthentication();
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); header('Allow: POST'); exit; }
$id = idPositivoMarca($_POST['id_marca'] ?? null); [$values, $errors] = validarMarca($_POST); $formUrl = appUrl('admin/marcas/editar.php?id=' . ($id ?? 0));
if (!validateCsrfToken($_POST['csrf_token'] ?? null)) { guardarEstadoMantenedor('marca_editar_' . ($id ?? 0), $values, [], 'La solicitud no es válida.'); header('Location: ' . $formUrl, true, 303); exit; }
if ($id === null) { http_response_code(404); exit; } if ($errors !== []) { guardarEstadoMantenedor('marca_editar_' . $id, $values, $errors); header('Location: ' . $formUrl, true, 303); exit; }
try { $connection = database(); if (obtenerMarca($connection, $id) === null) { http_response_code(404); exit; } if (existeNombreMarca($connection, $values['nombre'], $id)) { guardarEstadoMantenedor('marca_editar_' . $id, $values, ['nombre' => 'Ya existe una marca con este nombre.']); header('Location: ' . $formUrl, true, 303); exit; } $slug = generarSlugUnicoMantenedor($connection, 'marcas', 'id_marca', $values['nombre'], $id); $statement = $connection->prepare('UPDATE marcas SET nombre = :nombre, slug = :slug, activo = :activo, actualizado_en = CURRENT_TIMESTAMP WHERE id_marca = :id'); $statement->execute(['nombre' => $values['nombre'], 'slug' => $slug, 'activo' => $values['activo'], 'id' => $id]); header('Location: ' . appUrl('admin/marcas/index.php?mensaje=actualizada'), true, 303); exit; } catch (Throwable $exception) { $duplicate = $exception->getCode() === '23505'; error_log('Brand update error: ' . $exception->getMessage()); guardarEstadoMantenedor('marca_editar_' . $id, $values, $duplicate ? ['nombre' => 'Ya existe una marca con este nombre.'] : [], $duplicate ? null : 'No fue posible actualizar la marca.'); header('Location: ' . $formUrl, true, 303); exit; }
